### PR TITLE
Alter parallel() and group() functionality

### PR DESCRIPTION
**Pull request by clethrill**
Reasons for this pull request can be seen in [issue 58](https://github.com/creationix/step/issues/58). 

One possible issue, up to the author is that I make use of the spread and rest operators (...) which is only available from node version 6.0.0 and onwards.

### CODE REVIEW

**Review by creationix — COMMENTED** [review]
The diff is messy because you re-indented most all the code.  Could you have a clean diff without the whitespace changes?

**Comment by jasonsperske** [comment]
Just wrote a simple jsperf and found a rather wide difference between arguments and spread syntax (at least on Firefox).  Any idea if my testing methodology is off?  https://jsperf.com/spread-syntax-vs-arguments/1

**Comment by clethrill** [comment]
I have seen these replies. Will get around to replying soon hopefully.

**Comment by clethrill** [comment]
I used your performance tests on two separate machines, one with mac chrome and the other window chrome and firefox. Mac on both showed name arguments fastest with spread and implicit arguments access similarly behind and arguments way behind. I got the same sort of results as you suggested on firefox though.

I ran a [similar test](https://pastebin.com/jmzNJCYg) on machine on node.js v6.3.1 and got similar results to firefox performance.

However, in either case, either the spread syntax `...` or `slice.call(arguments)` needs to be used for this to work (as far as I'm aware) because it accounts for _n_ arguments. It also makes the code much more readable, which I noticed someone else made a pull request for.

**Pull request closed without merging**
